### ISSUE TITLE
dist 里面没有 app.json ,你们是怎么打开的？

### ISSUE THREAD

**Issue by nearxu** [cheesekun/wx-github#2]

**Comment by cheesekun** [comment]
有的。发一下你打包后的文件目录，看下 @nearxu

**Comment by nearxu** [comment]
![image](https://user-images.githubusercontent.com/18578033/44638497-b8efd680-a9e9-11e8-817d-9b9ff9d929fa.png)

**Comment by nearxu** [comment]
已经解决了，主要是新版本对老版本的问题。
把 packpage.json 里的 mpvue-loade 后面的‘^’去掉，重新安装依赖
