### ISSUE TITLE
为什么auth不存到vuex里，而是用wx.setStorageSync来保存？

### ISSUE THREAD

**Issue by syyzz3** [cheesekun/wx-github#5]
如标题
看到您项目中，auth用setStorageSync来保存，既然使用了vuex为什么不会用vuex保存呢？
`
const authStr = JSON.stringify(auth)
wx.setStorageSync('auth', authStr)
this.comfirmLogin(true)
`

**Comment by cheesekun** [comment]
`vuex`只能是临时保存（小程序开启到关闭阶段），`setStorageSync`能存到本地，就像浏览器的`localstorage`

**Comment by syyzz3** [comment]
@cheesekun auth这个数据要持久化保存，是为了避免每次使用都登录吗？如何另一个用户通过这个手机想要登录怎么办？

**Comment by cheesekun** [comment]
是为了避免每次都登录。
我没有做退出登录的功能哈哈哈。我觉得没必要，很少有别人用你手机登录小程序这种场景吧.
其实可以手动清除当前小程序的缓存，但是应该大多数用户也不懂吧。
@syyzz3
